/* eslint-disable react/no-unescaped-entities */
import { useEffect, useState } from "react";
import "@/App.css";
import { ArrowUpRight, ChevronDown, Code2, Download, ExternalLink, Mail, MapPin, Moon, Send, Sun, Terminal, Zap } from "lucide-react";

const roles = ["Java & Spring Boot Developer", "Backend Systems Engineer", "AI/ML Enthusiast"];
const projects = [
  { name: "latent-diffusion-model", icon: "◈", color: "green", stack: ["Python", "PyTorch", "VAE"], blurb: "Resource-efficient text-to-image generation with compressed latent representations.", details: "Designed a latent diffusion pipeline using VAE-based compression to boost prompt guidance by 46.8% while reducing computational load by 48x." },
  { name: "text-summarization-tool", icon: "≡", color: "cyan", stack: ["Python", "NLP", "Transformers"], blurb: "A focused NLP tool for turning long-form content into clear, useful summaries.", details: "Built a summarization workflow that preserves key context and produces concise outputs for fast reading and downstream analysis." },
  { name: "openai-chatbot", icon: "✦", color: "amber", stack: ["Python", "OpenAI", "API"], blurb: "Conversational assistant with clean prompt routing and a human-first interface.", details: "Created an interactive chatbot prototype with structured prompts, conversational context, and practical error handling." },
];
const skills = { Languages: ["Java", "Python", "SQL", "JavaScript"], Backend: ["Spring Boot", "REST APIs", "Microservices", "J2EE"], "AI / ML": ["LLMs", "RAGs", "Prompt Engineering", "Diffusion & Generative Models"], Databases: ["MySQL", "MongoDB", "Distributed DBs"], Tools: ["Git", "Linux", "Docker", "Azure"] };
const certs = [
  ["Ivanti", "Software Engineering Internship Certificate", "https://drive.google.com/file/d/1pLUe0OKJNgRsG2h792dB-Tsf5K2CQmBM/view?usp=sharing"],
  ["Google Cloud", "Vertex AI + Generative AI", "https://www.credly.com/badges/e5ab8a83-5150-4cd1-8a28-5a454d0eb702/public_url"],
  ["HackerRank", "Java Certification", "https://www.hackerrank.com/certificates/iframe/b8fc8561d396"],
  ["HackerRank", "SQL (Advanced)", "https://www.hackerrank.com/certificates/iframe/34c93d96407e"],
  ["GitHub", "Professional Certificate", "https://www.linkedin.com/learning/certificates/a7238ef68df0d4ffe18a69b5aff1d754083967883d063646832d87b4fa398396?trk=share_certificate"],
];

function App() {
  const [booted, setBooted] = useState(false); const [light, setLight] = useState(false); const [roleIndex, setRoleIndex] = useState(0); const [roleText, setRoleText] = useState(""); const [expanded, setExpanded] = useState(null); const [sent, setSent] = useState(false); const [message, setMessage] = useState(""); const [time, setTime] = useState("");
  useEffect(() => { const boot = setTimeout(() => setBooted(true), 2200); return () => clearTimeout(boot); }, []);
  useEffect(() => { let i = 0; let deleting = false; const timer = setInterval(() => { const target = roles[roleIndex]; if (!deleting) { setRoleText(target.slice(0, i + 1)); i += 1; if (i === target.length) { deleting = true; } } else { setRoleText(target.slice(0, i - 1)); i -= 1; if (i === 0) { deleting = false; setRoleIndex((x) => (x + 1) % roles.length); } } }, deleting ? 45 : i === roles[roleIndex].length ? 1300 : 65); return () => clearInterval(timer); }, [roleIndex]);
  useEffect(() => { const tick = () => setTime(new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date())); tick(); const t = setInterval(tick, 1000); return () => clearInterval(t); }, []);
  const go = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const submit = (e) => { e.preventDefault(); if (message.toLowerCase().includes("sudo")) setSent("sudo access granted — fun fact: Harsha can debug faster than this terminal can blink."); else setSent("Message staged successfully. Open your email client to send it directly."); };
  if (!booted) return <div className="boot-screen"><div className="boot-lines"><p><span>root@harsha-dev</span>:~$ ./initialize_portfolio</p><p className="dim">Loading modules... [OK]</p><p className="dim">Mounting experience... [OK]</p><p className="green">Welcome, recruiter.</p><p className="boot-name">Harshavardhan Porika<span className="cursor-block">▋</span></p><p className="dim">Backend Software Engineer</p></div><button className="skip-boot" data-testid="skip-boot-button" onClick={() => setBooted(true)}>skip boot ↵</button></div>;
  return <div className={light ? "app light" : "app"}>
    <div className="matrix" aria-hidden="true">{Array.from({ length: 22 }, (_, i) => <span key={i} style={{ left: `${(i * 7) % 100}%`, animationDelay: `${i * -0.7}s` }}>01·λ·10·/·{i}</span>)}</div>
    <header className="topbar"><a className="brand" href="#home" data-testid="brand-home"><span className="brand-mark">&gt;_</span><span>harsha<span className="green">.dev</span></span></a><nav className="tabs" aria-label="Main navigation">{[["home","01 / home"],["experience","02 / experience"],["projects","03 / projects"],["skills","04 / skills"],["contact","05 / contact"]].map(([id,label]) => <button key={id} data-testid={`nav-${id}-button`} onClick={() => go(id)}>{label}</button>)}</nav><button className="theme-toggle" data-testid="theme-toggle-button" onClick={() => setLight(!light)} aria-label="Toggle light mode">{light ? <Moon size={16}/> : <Sun size={16}/>}<span>{light ? "dark" : "light"}</span></button></header>
    <main>
      <section id="home" className="hero section-pad"><div className="hero-copy"><p className="eyebrow"><span className="green">$</span> whoami <span className="muted">// available for backend roles</span></p><h1>Harshavardhan<br/><span className="outline">Porika</span><span className="green">.</span></h1><p className="role"><span className="cyan">const</span> role = <span className="green">"{roleText}"</span><span className="cursor-block">▋</span></p><p className="hero-summary">Computer Science graduate with production-level experience building resilient Java systems for global enterprise environments.</p><div className="hero-actions"><button className="primary-btn" data-testid="hero-contact-button" onClick={() => go("contact")}>Let’s connect <ArrowUpRight size={16}/></button><a className="text-btn" data-testid="hero-resume-link" href="https://docs.google.com/document/d/1HhgoElRugWK8nDcCbE55bLdGpi4D0EvFRd2VI9kF7ls/edit?usp=sharing" target="_blank" rel="noreferrer"><Download size={15}/> resume.pdf</a></div></div><div className="hero-status"><span className="status-dot"></span><span>IST / HYDERABAD</span><strong data-testid="ist-clock">{time}</strong><small>system status: <i>online</i></small></div><div className="scroll-cue">scroll to explore <ChevronDown size={14}/></div></section>
      <section id="about" className="section-pad split-section reveal"><div className="section-label"><span>01</span><h2>About me</h2></div><div className="about-grid"><div><p className="lead">I like solving the failures that happen after the happy path.</p><p className="body-copy">I’m a Computer Science graduate at Neil Gogte Institute of Technology, with one year inside production-level enterprise software at Ivanti. My work sits where backend engineering, network behavior, and customer impact meet.</p><p className="body-copy">Currently looking for an Associate Software Backend Engineer role where I can ship reliable systems and keep learning in public.</p></div><div className="terminal-card" data-testid="whoami-card"><div className="window-bar"><span></span><span></span><span></span><b>whoami.sh</b></div><div className="terminal-content"><p className="muted">$ cat ./profile.json</p><p>&#123;</p><p>&nbsp;&nbsp;<span className="cyan">"name"</span>: <span className="green">"Harshavardhan Porika"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"role"</span>: <span className="green">"Backend Software Engineer"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"college"</span>: <span className="green">"NGIT"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"gpa"</span>: <span className="amber">8.7</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"grad"</span>: <span className="amber">2026</span></p><p>&#125;</p></div></div></div></section>
      <section id="experience" className="section-pad reveal"><div className="section-label"><span>02</span><h2>Experience</h2></div><div className="experience-card"><div className="exp-heading"><div><p className="green mono">commit 8f4a2c1 <span className="muted">(HEAD → production)</span></p><h3>Software Engineering Intern <span>@ Ivanti</span></h3><p className="muted">Aug 2025 — July 2026 · Enterprise MDM / UEM</p></div><span className="tag">1 year / shipped</span></div><div className="commit-list">{["Reduced engineering bug backlog by 18% by resolving 50+ customer-facing production defects through Java debugging and deep log analysis.","Deployed 10+ critical OWASP-aligned hotfixes and backported vulnerability patches as RPM packages outside sprint cycles.","Optimized Java batch processing to unblock iOS device associations for global enterprise client F. Hoffmann-La Roche AG.","Resolved 40+ Sev-1/2/3 incidents for BlackRock and Morgan Stanley using SQL-driven analysis across distributed infrastructure.","Fixed Microsoft Graph API regressions, restoring managed-app visibility and automated policy sync across iOS and Android.","Designed an efficient LDM with Python, PyTorch and VAE compression, improving prompt guidance by 46.8% and cutting compute 48x."].map((item, i) => <div className="commit" key={item}><span className="commit-hash">{["a1d9e40","c22bf81","e03cc9a","f1142ad","b5e6d0c","8f4a2c1"][i]}</span><p>{item}</p><span className="blame">{["Sep 25","Oct 25","Nov 25","Jan 26","Mar 26","Jun 26"][i]}</span></div>)}</div></div></section>
      <section id="projects" className="section-pad reveal"><div className="section-label"><span>03</span><h2>Selected projects</h2></div><div className="project-grid">{projects.map((project, i) => <article className="repo-card" key={project.name} data-testid={`project-card-${i}`}><div className="repo-top"><span className={`repo-icon ${project.color}`}>{project.icon}</span><span className="repo-status"><span className="status-dot"></span> public</span></div><h3>{project.name}</h3><p>{project.blurb}</p><div className="stack">{project.stack.map(tag => <span key={tag}>{tag}</span>)}</div><button className="readme-btn" data-testid={`project-readme-${i}-button`} onClick={() => setExpanded(expanded === i ? null : i)}>README.md <ChevronDown size={14} className={expanded === i ? "rotate" : ""}/></button>{expanded === i && <div className="readme" data-testid={`project-readme-${i}-content`}><span className="green">## overview</span><p>{project.details}</p></div>}</article>)}</div></section>
      <section id="skills" className="section-pad reveal"><div className="section-label"><span>04</span><h2>Skills / dependencies</h2></div><div className="skills-grid">{Object.entries(skills).map(([category, items]) => <div className="skill-group" key={category}><p className="group-title"><span className="cyan">"{category}"</span>: [</p>{items.map(item => <span className="skill-tag" data-testid={`skill-${item.toLowerCase().replaceAll(" ", "-")}`} key={item}>"{item}"</span>)}<p className="group-title">]</p></div>)}</div></section>
      <section className="section-pad reveal"><div className="section-label"><span>05</span><h2>Certifications</h2></div><div className="cert-grid">{certs.map(([issuer, name, url], i) => <a className="cert" data-testid={`certification-${i}-link`} href={url} target="_blank" rel="noreferrer" key={name}><span className="cert-icon">✓</span><span><b>{issuer}</b><small>{name}</small></span><ExternalLink size={14}/></a>)}</div></section>
      <section id="contact" className="section-pad contact-section reveal"><div className="section-label"><span>06</span><h2>Let’s talk</h2></div><div className="contact-grid"><div><p className="lead">Have a backend problem worth solving?</p><p className="body-copy">I’m open to conversations about associate backend engineering roles, production systems, and thoughtful AI/ML applications.</p><div className="direct-links"><a data-testid="email-link" href="mailto:porikaharsha1427@gmail.com"><Mail size={16}/> porikaharsha1427@gmail.com</a><a data-testid="linkedin-link" href="https://linkedin.com/in/harsha0252" target="_blank" rel="noreferrer"><ExternalLink size={16}/> linkedin.com/in/harsha0252</a></div></div><form className="contact-terminal" data-testid="contact-form" onSubmit={submit}><div className="window-bar"><span></span><span></span><span></span><b>contact — bash</b></div><div className="form-body"><label htmlFor="message"><span className="green">$</span> enter your message_</label><textarea id="message" data-testid="contact-message-input" value={message} onChange={e => setMessage(e.target.value)} placeholder="Type 'sudo' for a surprise..." required></textarea><button className="primary-btn" data-testid="contact-submit-button" type="submit"><Send size={15}/> execute send</button>{sent && <p className="form-result" data-testid="contact-success-message">{sent}</p>}</div></form></div></section>
    </main><footer><span><span className="green">&gt;_</span> built with curiosity</span><span>© 2026 Harshavardhan Porika</span><span><Zap size={13} className="green"/> open to opportunities</span></footer>
  </div>;
}

export default App;
