/* eslint-disable react/no-unescaped-entities */
import { Suspense, lazy, useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import Tilt from "@/components/Tilt";
import LogStream from "@/components/LogStream";
import ProjectsIDE from "@/components/ProjectsIDE";
import MatrixRain from "@/components/MatrixRain";
import "@/App.css";
import { ArrowUpRight, ChevronDown, Download, ExternalLink, Github, Mail, Moon, Send, Sun, Zap } from "lucide-react";

const HeroParticles = lazy(() => import("@/components/HeroParticles"));
const fadeUp = { hidden: { opacity: 0, y: 26 }, show: (i) => ({ opacity: 1, y: 0, transition: { delay: 0.25 + i * 0.14, duration: 0.65, ease: [0.22, 1, 0.36, 1] } }) };

const roles = ["Software Engineer", "Java & Spring Boot Developer", "AI/ML Enthusiast"];
const projects = [
  { name: "db-engine", icon: "▤", color: "cyan", repo: "https://github.com/Harsha-0252/db-engine", stack: ["Java 21", "Maven", "JUnit 5"], blurb: "A relational database engine built from scratch in Java 21 — slotted pages, a buffer pool with LRU eviction, a disk-backed B+Tree, and a hand-written SQL parser.", details: "# Java Relational Database Engine\n\n## Overview\nA relational database engine built from scratch in Java 21 — slotted pages, a buffer pool with LRU eviction, a disk-backed B+Tree, and a hand-written SQL parser.\n\n## Key Features\n• Custom lexer + recursive-descent SQL parser (no regex-based matching), producing an AST\n• Buffer pool manager bridging memory and disk with LRU eviction\n• Slotted-page storage layout (4096-byte pages) with a disk-backed B+Tree index\n• Transactions via an in-memory overlay (read-your-own-writes semantics) with COMMIT/ROLLBACK\n• Full SQL: CREATE/DROP/ALTER TABLE, INSERT/UPDATE/DELETE, SELECT with JOIN, GROUP BY, ORDER BY, aggregates\n\n## Scoped Limitations\n• Non-durable transactions (no WAL yet)\n• Full table scans — B+Tree is implemented but not yet wired into the query path\n\n## Testing\nJUnit 5 plus targeted adversarial testing: transaction isolation, byte-offset correctness across mixed fixed/variable-width columns, and constraint enforcement." },
  { name: "notiflow", icon: "≋", color: "green", repo: "https://github.com/Harsha-0252/notiflow", stack: ["Spring Boot", "RabbitMQ", "Redis", "Resilience4j"], blurb: "A resilient notification delivery pipeline built with Spring Boot 3, RabbitMQ, and Redis, wiring together four production resilience patterns end to end.", details: "# Notiflow\n\n## Overview\nA resilient notification delivery pipeline built with Spring Boot 3, RabbitMQ, and Redis — four production resilience patterns wired end to end.\n\n## Resilience Patterns\n• Idempotency via Redis SETNX with TTL — duplicate requests short-circuit safely\n• Async queueing through a RabbitMQ direct exchange — the HTTP path never blocks on delivery\n• Retry with exponential backoff (Spring Retry, 3 attempts) for transient failures\n• Circuit breaker (Resilience4j) that opens after a sustained failure threshold and auto-recovers via half-open state\n• Dead-letter queue (DLX + DLQ) for messages that exhaust retries, with a stats endpoint\n\n## Design\nDelivery gateway is a swappable interface — simulated by default; drop in a real SES/Twilio/SendGrid client without touching the resilience layers.\n\n## Testing\nUnit tests (no Docker needed) plus Docker-based integration tests covering end-to-end delivery, retry/DLQ behavior, and circuit breaker state transitions." },
  { name: "latent-diffusion-model", icon: "◈", color: "green", repo: "https://github.com/Harsha-0252/major-project", stack: ["Python", "PyTorch", "VAE"], blurb: "Resource-efficient text-to-image generation with compressed latent representations.", details: "# Latent Diffusion Model for Text-to-Image Synthesis\n\n## Overview\nAn efficient LDM that transforms natural language into high-fidelity visuals in compressed latent space, reducing compute while avoiding GAN-style mode collapse.\n\n## Key Features\n• VAE latent-space denoising\n• Frozen OpenAI CLIP conditioning with cross-attention\n• PyTorch AMP mixed precision for up to 50% less GPU memory\n• Gradio UI with inference-step and CFG controls\n\n## Architecture & Results\nPyTorch · diffusers · transformers / CLIP · MS-COCO 2014 · Gradio\nInception Score: 6.64 ± 0.45, outperforming AttnGAN by 46.8%; stable 128×128 generation across 11 epochs." },
  { name: "text-summarization-tool", icon: "≡", color: "cyan", repo: "https://github.com/Harsha-0252/text-summarization", stack: ["Python", "NLP", "Transformers"], blurb: "A focused NLP tool for turning long-form content into clear, useful summaries.", details: "# NLP Text Summarization Tool\n\n## Overview\nAn intelligent web application that condenses long-form documents into concise, accurate summaries while preserving semantic meaning.\n\n## Key Features\n• PDF and TXT parsing\n• Fine-tuned Hugging Face Pegasus abstractive summarization\n• Responsive interface with real-time results\n• Node.js bridge to the Python inference engine\n\n## Tech Stack\nJavaScript · HTML/CSS · Node.js · Python · Transformers / Pegasus" },
  { name: "openai-chatbot", icon: "✦", color: "amber", stack: ["Python", "OpenAI", "API"], blurb: "Conversational assistant with clean prompt routing and a human-first interface.", details: "# Context-Aware OpenAI Chatbot\n\n## Overview\nA full-stack conversational application that maintains context across multiple turns through the OpenAI GPT API.\n\n## Key Features\n• Session chat history for relevant multi-turn dialogue\n• Responsive desktop and mobile experience\n• Fast real-time request handling\n• Secure Next.js frontend with Node.js API routing\n\n## Tech Stack\nNext.js · JavaScript · Node.js · Python scripts · OpenAI GPT API" },
];
const skills = { Languages: ["Java", "Python", "SQL", "JavaScript", "C", "HTML / CSS3"], Backend: ["Spring Boot", "REST APIs", "Microservices", "J2EE"], "AI / ML": ["LLMs", "RAGs", "Prompt Engineering", "Diffusion & Generative Models"], Databases: ["MySQL", "MongoDB", "Redis", "Distributed DBs"], Tools: ["Git", "Linux", "Docker", "Azure", "Maven", "Jenkins"], "Core Engineering Concepts": ["DSA", "OOPS", "System Design", "CN", "OS", "Log Analysis & Debugging"] };
const certs = [
  ["Ivanti", "Software Engineering Internship Certificate", "https://drive.google.com/file/d/1pLUe0OKJNgRsG2h792dB-Tsf5K2CQmBM/view?usp=sharing"],
  ["Google Cloud", "Vertex AI + Generative AI", "https://www.credly.com/badges/e5ab8a83-5150-4cd1-8a28-5a454d0eb702/public_url"],
  ["HackerRank", "Java Certification", "https://www.hackerrank.com/certificates/iframe/b8fc8561d396"],
  ["HackerRank", "SQL (Advanced)", "https://www.hackerrank.com/certificates/iframe/34c93d96407e"],
  ["GitHub", "Professional Certificate", "https://www.linkedin.com/learning/certificates/a7238ef68df0d4ffe18a69b5aff1d754083967883d063646832d87b4fa398396?trk=share_certificate"],
];

function App() {
  const [booted, setBooted] = useState(false); const [light, setLight] = useState(false); const [roleIndex, setRoleIndex] = useState(0); const [roleText, setRoleText] = useState(""); const [sent, setSent] = useState(false); const [message, setMessage] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [sending, setSending] = useState(false); const [time, setTime] = useState(""); const [show3D, setShow3D] = useState(false); const [matrix, setMatrix] = useState(false);
  const reduceMotion = useReducedMotion();
  useEffect(() => { const boot = setTimeout(() => setBooted(true), 2200); return () => clearTimeout(boot); }, []);
  useEffect(() => { let i = 0; let deleting = false; const timer = setInterval(() => { const target = roles[roleIndex]; if (!deleting) { setRoleText(target.slice(0, i + 1)); i += 1; if (i === target.length) { deleting = true; } } else { setRoleText(target.slice(0, i - 1)); i -= 1; if (i === 0) { deleting = false; setRoleIndex((x) => (x + 1) % roles.length); } } }, deleting ? 45 : i === roles[roleIndex].length ? 1300 : 65); return () => clearInterval(timer); }, [roleIndex]);
  useEffect(() => { const tick = () => setTime(new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date())); tick(); const t = setInterval(tick, 1000); return () => clearInterval(t); }, []);
  useEffect(() => { if (!booted) return undefined; const capable = window.matchMedia("(min-width: 769px)").matches && !window.matchMedia("(prefers-reduced-motion: reduce)").matches; if (!capable) return undefined; const t = setTimeout(() => setShow3D(true), 500); return () => clearTimeout(t); }, [booted]);
  const go = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const submit = async (e) => { e.preventDefault(); if (message.toLowerCase().includes("sudo")) { setMatrix(true); setMessage(""); return; } setSending(true); setSent(false); try { const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/contact`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, message }) }); if (!response.ok) throw new Error("send failed"); setSent("Message sent successfully — Harshavardhan will get back to you soon."); setMessage(""); } catch (error) { setSent("Unable to send right now. Please use the direct email link below."); } finally { setSending(false); } };
  if (!booted) return <div className="boot-screen"><div className="boot-lines"><p><span>root@harsha-dev</span>:~$ ./initialize_portfolio</p><p className="dim">Loading modules... [OK]</p><p className="dim">Mounting experience... [OK]</p><p className="green">Welcome, recruiter.</p><p className="boot-name">Harshavardhan Porika<span className="cursor-block">▋</span></p><p className="dim">Software Engineer</p></div><button className="skip-boot" data-testid="skip-boot-button" onClick={() => setBooted(true)}>skip boot ↵</button></div>;
  return <div className={light ? "app light" : "app"}>
    <div className="matrix" aria-hidden="true">{Array.from({ length: 22 }, (_, i) => <span key={i} style={{ left: `${(i * 7) % 100}%`, animationDelay: `${i * -0.7}s` }}>01·λ·10·/·{i}</span>)}</div>
    {matrix && <MatrixRain onClose={() => setMatrix(false)} />}
    <header className="topbar"><a className="brand" href="#home" data-testid="brand-home"><span className="brand-mark">&gt;_</span><span>harsha<span className="green">.dev</span></span></a><nav className="tabs" aria-label="Main navigation">{[["home","01 / home"],["experience","02 / experience"],["projects","03 / projects"],["skills","04 / skills"],["contact","05 / contact"]].map(([id,label]) => <button key={id} data-testid={`nav-${id}-button`} onClick={() => go(id)}>{label}</button>)}</nav><button className="theme-toggle" data-testid="theme-toggle-button" onClick={() => setLight(!light)} aria-label="Toggle light mode">{light ? <Moon size={16}/> : <Sun size={16}/>}<span>{light ? "dark" : "light"}</span></button></header>
    <main>
      <section id="home" className="hero section-pad">{show3D && <Suspense fallback={null}><HeroParticles /></Suspense>}<motion.div className="hero-copy" initial="hidden" animate="show"><motion.p className="eyebrow" custom={0} variants={fadeUp}><span className="green">$</span> whoami <span className="muted">// available for software engineer roles</span></motion.p><motion.h1 custom={1} variants={fadeUp}><span className="glitch" data-text="Harshavardhan">Harshavardhan</span><br/><span className="glitch outline" data-text="Porika">Porika</span><span className="green">.</span></motion.h1><motion.p className="role" custom={2} variants={fadeUp}><span className="cyan">const</span> role = <span className="green">"{roleText}"</span><span className="cursor-block">▋</span></motion.p><motion.p className="hero-summary" custom={3} variants={fadeUp}>Computer Science graduate with production-level experience building resilient Java systems for global enterprise environments.</motion.p><motion.div className="hero-actions" custom={4} variants={fadeUp}><button className="primary-btn" data-testid="hero-contact-button" onClick={() => go("contact")}>Let’s connect <ArrowUpRight size={16}/></button><a className="text-btn" data-testid="hero-resume-link" href="https://docs.google.com/document/d/1HhgoElRugWK8nDcCbE55bLdGpi4D0EvFRd2VI9kF7ls/export?format=pdf" download="Harshavardhan-Porika-Resume.pdf" rel="noreferrer"><Download size={15}/> download resume.pdf</a></motion.div></motion.div><motion.div className="hero-status" data-testid="hero-status-panel" initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0, transition: { delay: 1.1, duration: 0.6 } }}><span className="status-dot"></span><span>IST / HYDERABAD</span><strong data-testid="ist-clock">{time}</strong><small>system status: <i>online</i></small><div className="metrics" data-testid="system-metrics"><span className="metric"><em>cpu</em><i className="bar"><b className="m-cpu"></b></i><em className="val">23%</em></span><span className="metric"><em>mem</em><i className="bar"><b className="m-mem"></b></i><em className="val">41%</em></span><span className="metric"><em>net</em><i className="bar"><b className="m-net"></b></i><em className="val">12ms</em></span></div></motion.div><div className="scroll-cue">scroll to explore <ChevronDown size={14}/></div></section>
      <section id="about" className="section-pad split-section reveal"><LogStream /><div className="section-label"><span>01</span><h2>About me</h2></div><div className="about-grid"><div><p className="lead">I like solving the failures that happen after the happy path.</p><p className="body-copy">I’m a Computer Science graduate at Neil Gogte Institute of Technology, with one year inside production-level enterprise software at Ivanti. My work sits where backend engineering, network behavior, and customer impact meet.</p><p className="body-copy">Currently looking for an Associate Software Engineer role where I can ship reliable systems and keep learning in public.</p></div><Tilt className="terminal-card glass" data-testid="whoami-card"><div className="window-bar"><span></span><span></span><span></span><b>whoami.sh</b></div><div className="terminal-content"><p className="muted">$ cat ./profile.json</p><p>&#123;</p><p>&nbsp;&nbsp;<span className="cyan">"name"</span>: <span className="green">"Harshavardhan Porika"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"role"</span>: <span className="green">"Software Engineer"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"college"</span>: <span className="green">"NGIT"</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"gpa"</span>: <span className="amber">8.7</span>,</p><p>&nbsp;&nbsp;<span className="cyan">"grad"</span>: <span className="amber">2026</span></p><p>&#125;</p></div></Tilt></div></section>
      <section id="experience" className="section-pad reveal"><LogStream /><div className="section-label"><span>02</span><h2>Experience</h2></div><Tilt className="experience-card glass" max={3} data-testid="experience-card"><div className="exp-heading"><div><p className="green mono">commit 8f4a2c1 <span className="muted">(HEAD → production)</span></p><h3>Software Engineering Intern <span>@ Ivanti</span></h3><p className="muted">Aug 2025 — July 2026 · Enterprise MDM / UEM · EPMM</p></div><span className="tag">1 year / shipped</span></div><div className="commit-list">{["Reduced engineering bug backlog by 18% by resolving 50+ customer-facing production defects through Java debugging and deep log analysis.","Deployed 10+ critical OWASP-aligned hotfixes and backported vulnerability patches as RPM packages outside sprint cycles.","Optimized Java batch processing to unblock iOS device associations for global enterprise client F. Hoffmann-La Roche AG.","Resolved 40+ Sev-1/2/3 incidents for BlackRock and Morgan Stanley using SQL-driven analysis across distributed infrastructure.","Fixed Microsoft Graph API regressions, restoring managed-app visibility and automated policy sync across iOS and Android.","Designed an efficient LDM with Python, PyTorch and VAE compression, improving prompt guidance by 46.8% and cutting compute 48x."].map((item, i) => <div className="commit" key={item}><span className="commit-hash">{["a1d9e40","c22bf81","e03cc9a","f1142ad","b5e6d0c","8f4a2c1"][i]}</span><p>{item}</p><span className="blame">{["Sep 25","Oct 25","Nov 25","Jan 26","Mar 26","Jun 26"][i]}</span></div>)}</div></Tilt></section>
      <section id="projects" className="section-pad reveal"><div className="section-label"><span>03</span><h2>Selected projects</h2></div><ProjectsIDE projects={projects} /></section>
      <section id="skills" className="section-pad reveal"><div className="section-label"><span>04</span><h2>Skills</h2></div><div className="skills-grid">{Object.entries(skills).map(([category, items]) => <div className="skill-group" key={category}><p className="group-title"><span className="cyan">"{category}"</span>: [</p>{items.map((item, j) => <motion.span className="skill-tag" data-testid={`skill-${item.toLowerCase().replaceAll(" ", "-")}`} key={item} animate={reduceMotion ? {} : { y: [0, -5, 0] }} transition={{ duration: 3.4 + (j % 3) * 0.8, repeat: Infinity, ease: "easeInOut", delay: j * 0.25 }} whileHover={{ scale: 1.06, color: "#00ff66" }}>"{item}"</motion.span>)}<p className="group-title">]</p></div>)}</div></section>
      <section className="section-pad reveal"><div className="section-label"><span>05</span><h2>Certifications</h2></div><div className="cert-grid">{certs.map(([issuer, name, url], i) => <a className="cert" data-testid={`certification-${i}-link`} href={url} target="_blank" rel="noreferrer" key={name}><span className="cert-icon">✓</span><span><b>{issuer}</b><small>{name}</small></span><ExternalLink size={14}/></a>)}</div></section>
      <section id="contact" className="section-pad contact-section reveal"><div className="section-label"><span>06</span><h2>Let’s talk</h2></div><div className="contact-grid"><div><p className="lead">Have a software engineering problem worth solving?</p><p className="body-copy">I’m open to conversations about software engineering roles, production systems, and thoughtful AI/ML applications.</p><div className="direct-links"><a data-testid="email-link" href="mailto:porikaharsha1427@gmail.com"><Mail size={16}/> porikaharsha1427@gmail.com</a><a data-testid="linkedin-link" href="https://linkedin.com/in/harsha0252" target="_blank" rel="noreferrer"><ExternalLink size={16}/> linkedin.com/in/harsha0252</a><a data-testid="github-link" href="https://github.com/Harsha-0252" target="_blank" rel="noreferrer"><Github size={16}/> github.com/Harsha-0252</a></div></div><form className="contact-terminal" data-testid="contact-form" onSubmit={submit}><div className="window-bar"><span></span><span></span><span></span><b>contact — bash</b></div><div className="form-body"><label htmlFor="name"><span className="green">$</span> enter your name_</label><input id="name" data-testid="contact-name-input" value={name} onChange={e => setName(e.target.value)} placeholder="Your name" required/><label htmlFor="email"><span className="green">$</span> enter your email_</label><input id="email" type="email" data-testid="contact-email-input" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required/><label htmlFor="message"><span className="green">$</span> enter your message_</label><textarea id="message" data-testid="contact-message-input" value={message} onChange={e => { if (e.target.value.toLowerCase().includes("sudo")) { setMatrix(true); setMessage(""); } else setMessage(e.target.value); }} placeholder="Type 'sudo' for a surprise..." required></textarea><button className="primary-btn" data-testid="contact-submit-button" type="submit" disabled={sending}><Send size={15}/> {sending ? "sending..." : "execute send"}</button>{sent && <p className="form-result" data-testid="contact-success-message">{sent}</p>}</div></form></div></section>
    </main><footer><span><span className="green">&gt;_</span> built with curiosity</span><span>© 2026 Harshavardhan Porika</span><a className="footer-gh" data-testid="footer-github-link" href="https://github.com/Harsha-0252" target="_blank" rel="noreferrer"><Github size={13}/> Harsha-0252</a><span><Zap size={13} className="green"/> open to opportunities</span></footer>
  </div>;
}

export default App;
